#### Data Cleaning

In [2]:
!pip3 install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (2.4.0)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: pip3 install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
# importing dataset
df = pd.read_excel('customer_data.xlsx')
df.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [5]:
# Identifying missing values
missing_value = df.isnull().sum()
print("Missing Values: ")
missing_value

Missing Values:

CustomerID                  0
Gender                      0
Age                         0
Income                      5
City                        3
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [6]:
# Handling Missing values
from sklearn.impute import SimpleImputer

# Handling missing values of Income
income = SimpleImputer(strategy = 'median')
income.fit(df[['Income']])
df[['Income']] = income.transform(df[['Income']])

# Handling missing values of City
city = SimpleImputer(strategy = 'most_frequent')
city.fit(df[['City']])
df[['City']] = city.transform(df[['City']])

In [7]:
# Identifying missing values
missing_value = df.isnull().sum()
print("Missing Values: ")
missing_value

Missing Values:

CustomerID                  0
Gender                      0
Age                         0
Income                      0
City                        0
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [8]:
# checking data types
df.dtypes

CustomerID                   object
Gender                       object
Age                           int64
Income                      float64
City                         object
Region                       object
Frequency_of_Purchases        int64
Average_Purchase_Amount     float64
Customer_Lifespan_Months     object
Purchase_Channel             object
Date_of_Purchase             object
Churn_Status                 object
dtype: object

In [9]:
# Checking invalid values
unique_values = df['Customer_Lifespan_Months'].unique()
print("Customer lifespan Months Values: ")
unique_values

Customer lifespan Months Values:

array([3, 4, 1, 2, 5, 'XXXX'], dtype=object)

In [10]:
# Removing Invalid Values
df = df[df['Customer_Lifespan_Months'] != 'XXXX']

In [11]:
# Checking invalid values
unique_values = df['Customer_Lifespan_Months'].unique()
print("Customer lifespan Months Values: ")
unique_values

Customer lifespan Months Values:

array([3, 4, 1, 2, 5], dtype=object)

In [12]:
# Converting Data Type to Integer
df['Customer_Lifespan_Months'] = df['Customer_Lifespan_Months'].astype(int)

In [13]:
# Converting Data Type to Datetime
df['Date_of_Purchase'] = pd.to_datetime(df['Date_of_Purchase'])

In [14]:
# checking data types
df.dtypes

CustomerID                          object
Gender                              object
Age                                  int64
Income                             float64
City                                object
Region                              object
Frequency_of_Purchases               int64
Average_Purchase_Amount            float64
Customer_Lifespan_Months             int64
Purchase_Channel                    object
Date_of_Purchase            datetime64[ns]
Churn_Status                        object
dtype: object

In [15]:
# Displaying dataset
df.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [16]:
# Checking Duplicate Data
duplicates = df.duplicated()
df[duplicates]

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
80,C021,Female,22,41743.0,Los Angeles,Northeast,4,54.599,1,Online,2023-06-08,No

In [17]:
# Removing Duplicate Data
df.drop_duplicates(inplace = True)

In [18]:
# Checking Duplicate Data
duplicates = df.duplicated()
df[duplicates]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status]
Index: []

### Sorting and Filtering

In [19]:
# sorting 
sorted_data = df.sort_values(by='Income', ascending = False)
sorted_data

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
55,C056,Female,29,107662.0,Houston,Northeast,3,47.877,1,In-store,2022-02-11,No
22,C023,Female,41,105186.0,Los Angeles,Midwest,14,137.697,4,Online,2023-07-15,Yes
70,C071,Female,36,103264.0,Los Angeles,Northeast,11,117.394,3,Online,2023-12-22,Yes
32,C033,Female,31,98590.0,Houston,West,7,76.114,2,Online,2023-06-30,No
52,C053,Female,45,90860.0,Houston,Northeast,10,105.287,3,In-store,2023-12-29,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
14,C015,Male,44,32500.0,New York,Northeast,9,96.473,3,Online,2023-03-30,No
49,C050,Female,39,29104.0,Houston,Midwest,7,84.461,2,Online,2022-03-17,No
10,C011,Female,53,27958.0,Los Angeles,Midwest,10,98.449,3,In-store,2023-07-16,Yes
23,C024,Male,54,27660.0,New York,Midwest,12,125.763,3,Online,2023-07-11,Yes
50,C051,Female,19,15531.0,Houston,Midwest,10,97.782,3,In-store,2022-09-24,Yes

In [20]:
# Filtering male data
male_data = df[df['Gender'] == 'Male']
male_data

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No
5,C006,Male,52,76470.0,Chicago,Midwest,11,117.012,3,Online,2022-11-30,Yes
7,C008,Male,38,38401.0,Houston,West,6,70.730,2,Online,2022-05-24,No
8,C009,Male,44,73105.0,Los Angeles,Northeast,12,124.887,3,Online,2022-09-02,Yes
14,C015,Male,44,32500.0,New York,Northeast,9,96.473,3,Online,2023-03-30,No
15,C016,Male,37,59214.0,Houston,Midwest,10,108.902,3,Online,2022-01-02,Yes
17,C018,Male,39,86730.0,New York,Midwest,11,118.579,3,Online,2022-03-06,Yes
18,C019,Male,32,41111.0,Los Angeles,West,14,133.229,4,Online,2023-07-19,Yes
19,C020,Male,28,37050.0,Los Angeles,Midwest,6,71.789,2,Online,2022-04-08,No
21,C022,Male,26,78988.0,Chicago,Midwest,7,76.826,2,In-store,2023-12-24,No
23,C024,Male,54,27660.0,New York,Midwest,12,125.763,3,Online,2023-07-11,Yes
24,C025,Male,27,45239.0,Los Angeles,West,12,127.888,3,In-store,2022-04-04,Yes
33,C034,Male,53,78203.0,Houston,Northeast,12,130.277,3,In-store,2023-06-05,Yes
34,C035,Male,28,50039.0,New York,West,7,75.568,2,Online,2022-09-14,No
35,C036,Male,23,43471.0,New York,West,5,65.357,1,Online,2022-08-12,No
38,C039,Male,43,51799.0,Houston,West,14,133.540,4,Online,2022-10-26,Yes
41,C042,Male,53,52616.0,Houston,Northeast,11,120.311,3,Online,2022-07-15,Yes
42,C043,Male,44,66344.0,Chicago,Midwest,12,130.562,3,In-store,2023-05-17,Yes
44,C045,Male,22,46979.0,Houston,West,8,86.904,2,Online,2022-12-29,No
45,C046,Male,44,59154.0,Chicago,West,15,152.291,4,Online,2022-12-07,Yes
48,C049,Male,49,58036.0,Los Angeles,West,12,129.524,3,Online,2022-11-24,Yes
53,C054,Male,31,51243.0,Houston,Northeast,7,73.408,2,Online,2023-09-26,No
57,C058,Male,18,39995.0,Houston,West,7,81.111,2,In-store,2022-04-12,No
59,C060,Male,35,82532.0,Houston,Midwest,6,68.405,1,Online,2022-10-16,No
60,C061,Male,24,53080.0,Los Angeles,West,16,193.046,5,In-store,2022-07-28,Yes
62,C063,Male,39,47127.0,New York,West,10,96.553,3,Online,2023-06-18,Yes
63,C064,Male,30,58033.0,Houston,West,10,107.919,3,In-store,2023-11-16,Yes
64,C065,Male,31,50889.0,New York,West,9,94.469,2,Online,2022-07-29,No
66,C067,Male,54,58033.0,Houston,West,12,128.255,3,Online,2022-03-24,Yes
69,C070,Male,36,58033.0,Chicago,Northeast,8,85.832,2,Online,2023-07-28,No
72,C073,Male,28,73631.0,Los Angeles,West,9,90.344,2,In-store,2022-11-20,No
75,C076,Male,44,59659.0,Houston,Midwest,14,134.540,4,Online,2023-12-25,Yes
77,C078,Male,30,76887.0,Houston,Midwest,7,80.816,2,Online,2022-11-14,No

In [21]:
# Filtering Male Customers with more than 5  Purchase Frequency
male_fre_data = male_data[male_data['Frequency_of_Purchases']>5]
male_fre_data

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
5,C006,Male,52,76470.0,Chicago,Midwest,11,117.012,3,Online,2022-11-30,Yes
7,C008,Male,38,38401.0,Houston,West,6,70.730,2,Online,2022-05-24,No
8,C009,Male,44,73105.0,Los Angeles,Northeast,12,124.887,3,Online,2022-09-02,Yes
14,C015,Male,44,32500.0,New York,Northeast,9,96.473,3,Online,2023-03-30,No
15,C016,Male,37,59214.0,Houston,Midwest,10,108.902,3,Online,2022-01-02,Yes
17,C018,Male,39,86730.0,New York,Midwest,11,118.579,3,Online,2022-03-06,Yes
18,C019,Male,32,41111.0,Los Angeles,West,14,133.229,4,Online,2023-07-19,Yes
19,C020,Male,28,37050.0,Los Angeles,Midwest,6,71.789,2,Online,2022-04-08,No
21,C022,Male,26,78988.0,Chicago,Midwest,7,76.826,2,In-store,2023-12-24,No
23,C024,Male,54,27660.0,New York,Midwest,12,125.763,3,Online,2023-07-11,Yes
24,C025,Male,27,45239.0,Los Angeles,West,12,127.888,3,In-store,2022-04-04,Yes
33,C034,Male,53,78203.0,Houston,Northeast,12,130.277,3,In-store,2023-06-05,Yes
34,C035,Male,28,50039.0,New York,West,7,75.568,2,Online,2022-09-14,No
38,C039,Male,43,51799.0,Houston,West,14,133.540,4,Online,2022-10-26,Yes
41,C042,Male,53,52616.0,Houston,Northeast,11,120.311,3,Online,2022-07-15,Yes
42,C043,Male,44,66344.0,Chicago,Midwest,12,130.562,3,In-store,2023-05-17,Yes
44,C045,Male,22,46979.0,Houston,West,8,86.904,2,Online,2022-12-29,No
45,C046,Male,44,59154.0,Chicago,West,15,152.291,4,Online,2022-12-07,Yes
48,C049,Male,49,58036.0,Los Angeles,West,12,129.524,3,Online,2022-11-24,Yes
53,C054,Male,31,51243.0,Houston,Northeast,7,73.408,2,Online,2023-09-26,No
57,C058,Male,18,39995.0,Houston,West,7,81.111,2,In-store,2022-04-12,No
59,C060,Male,35,82532.0,Houston,Midwest,6,68.405,1,Online,2022-10-16,No
60,C061,Male,24,53080.0,Los Angeles,West,16,193.046,5,In-store,2022-07-28,Yes
62,C063,Male,39,47127.0,New York,West,10,96.553,3,Online,2023-06-18,Yes
63,C064,Male,30,58033.0,Houston,West,10,107.919,3,In-store,2023-11-16,Yes
64,C065,Male,31,50889.0,New York,West,9,94.469,2,Online,2022-07-29,No
66,C067,Male,54,58033.0,Houston,West,12,128.255,3,Online,2022-03-24,Yes
69,C070,Male,36,58033.0,Chicago,Northeast,8,85.832,2,Online,2023-07-28,No
72,C073,Male,28,73631.0,Los Angeles,West,9,90.344,2,In-store,2022-11-20,No
75,C076,Male,44,59659.0,Houston,Midwest,14,134.540,4,Online,2023-12-25,Yes
77,C078,Male,30,76887.0,Houston,Midwest,7,80.816,2,Online,2022-11-14,No

In [22]:
# Filtering Churned Male Customers with more than 5 Purchase Frequency
churned_male_fre = male_fre_data.query('Churn_Status == "Yes"')
churned_male_fre

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
5,C006,Male,52,76470.0,Chicago,Midwest,11,117.012,3,Online,2022-11-30,Yes
8,C009,Male,44,73105.0,Los Angeles,Northeast,12,124.887,3,Online,2022-09-02,Yes
15,C016,Male,37,59214.0,Houston,Midwest,10,108.902,3,Online,2022-01-02,Yes
17,C018,Male,39,86730.0,New York,Midwest,11,118.579,3,Online,2022-03-06,Yes
18,C019,Male,32,41111.0,Los Angeles,West,14,133.229,4,Online,2023-07-19,Yes
23,C024,Male,54,27660.0,New York,Midwest,12,125.763,3,Online,2023-07-11,Yes
24,C025,Male,27,45239.0,Los Angeles,West,12,127.888,3,In-store,2022-04-04,Yes
33,C034,Male,53,78203.0,Houston,Northeast,12,130.277,3,In-store,2023-06-05,Yes
38,C039,Male,43,51799.0,Houston,West,14,133.540,4,Online,2022-10-26,Yes
41,C042,Male,53,52616.0,Houston,Northeast,11,120.311,3,Online,2022-07-15,Yes
42,C043,Male,44,66344.0,Chicago,Midwest,12,130.562,3,In-store,2023-05-17,Yes
45,C046,Male,44,59154.0,Chicago,West,15,152.291,4,Online,2022-12-07,Yes
48,C049,Male,49,58036.0,Los Angeles,West,12,129.524,3,Online,2022-11-24,Yes
60,C061,Male,24,53080.0,Los Angeles,West,16,193.046,5,In-store,2022-07-28,Yes
62,C063,Male,39,47127.0,New York,West,10,96.553,3,Online,2023-06-18,Yes
63,C064,Male,30,58033.0,Houston,West,10,107.919,3,In-store,2023-11-16,Yes
66,C067,Male,54,58033.0,Houston,West,12,128.255,3,Online,2022-03-24,Yes
75,C076,Male,44,59659.0,Houston,Midwest,14,134.540,4,Online,2023-12-25,Yes

In [23]:
# Filtering Churned Male Customers from Specific Cities
churned_male_freq_city = churned_male_fre[churned_male_fre['City'].isin(['Chicago', 'Houston'])]
churned_male_freq_city

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
5,C006,Male,52,76470.0,Chicago,Midwest,11,117.012,3,Online,2022-11-30,Yes
15,C016,Male,37,59214.0,Houston,Midwest,10,108.902,3,Online,2022-01-02,Yes
33,C034,Male,53,78203.0,Houston,Northeast,12,130.277,3,In-store,2023-06-05,Yes
38,C039,Male,43,51799.0,Houston,West,14,133.540,4,Online,2022-10-26,Yes
41,C042,Male,53,52616.0,Houston,Northeast,11,120.311,3,Online,2022-07-15,Yes
42,C043,Male,44,66344.0,Chicago,Midwest,12,130.562,3,In-store,2023-05-17,Yes
45,C046,Male,44,59154.0,Chicago,West,15,152.291,4,Online,2022-12-07,Yes
63,C064,Male,30,58033.0,Houston,West,10,107.919,3,In-store,2023-11-16,Yes
66,C067,Male,54,58033.0,Houston,West,12,128.255,3,Online,2022-03-24,Yes
75,C076,Male,44,59659.0,Houston,Midwest,14,134.540,4,Online,2023-12-25,Yes

In [24]:
# displaying dataset
df.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [25]:
# Displaying Selected Rows and Columns from Dataset
df.loc[0:4, 'CustomerID':'Region']

  CustomerID  Gender  Age   Income      City     Region
0       C001    Male   49  72504.0   Chicago  Northeast
1       C002  Female   38  40881.0  New York       West
2       C003    Male   17  63333.0  New York  Northeast
3       C004    Male   34  58030.0   Chicago    Midwest
4       C005    Male   30  78889.0   Houston    Midwest

In [26]:
# Displaying Dataset Using Index Positions
df.iloc[0:5, 0:6]

  CustomerID  Gender  Age   Income      City     Region
0       C001    Male   49  72504.0   Chicago  Northeast
1       C002  Female   38  40881.0  New York       West
2       C003    Male   17  63333.0  New York  Northeast
3       C004    Male   34  58030.0   Chicago    Midwest
4       C005    Male   30  78889.0   Houston    Midwest

In [27]:
# Filtering Customers Based on Lifespan Range
print("Customers with Lifespan Between 2 and 5 Months: ")
df[(df['Customer_Lifespan_Months'] >= 2) & (df['Customer_Lifespan_Months'] <=5 )]

Customers with Lifespan Between 2 and 5 Months:

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,9.824100e+01,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,1.576400e+02,4,In-store,2023-07-08,Yes
5,C006,Male,52,76470.0,Chicago,Midwest,11,1.170120e+02,3,Online,2022-11-30,Yes
6,C007,Female,35,60349.0,Houston,Northeast,9,9.554400e+01,2,In-store,2023-07-20,No
7,C008,Male,38,38401.0,Houston,West,6,7.073000e+01,2,Online,2022-05-24,No
...,...,...,...,...,...,...,...,...,...,...,...,...
72,C073,Male,28,73631.0,Los Angeles,West,9,9.034400e+01,2,In-store,2022-11-20,No
75,C076,Male,44,59659.0,Houston,Midwest,14,1.345400e+02,4,Online,2023-12-25,Yes
77,C078,Male,30,76887.0,Houston,Midwest,7,8.081600e+01,2,Online,2022-11-14,No
78,C079,Female,42,56569.0,New York,West,11,1.342341e+07,3,In-store,2022-12-08,Yes
79,C080,Female,26,43931.0,Los Angeles,Northeast,9,9.153600e+01,2,In-store,2023-09-18,No

#### Joining Data

In [28]:
# Second Dataset
# importing dataset
df2 = pd.read_excel('performance_data.xlsx')
df2.head()

  CustomerID  Recency  Frequency_Score  Monetary_Score
0       C001        3                2               2
1       C002        3                3               3
2       C003        4                4               4
3       C004        2                2               2
4       C005        1                1               1

In [29]:
# Merging Two Datasets Using Inner Join
joined_data = pd.merge(df,df2, on='CustomerID', how='inner')
joined_data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes,3,2,2
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes,3,3,3
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No,4,4,4
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No,2,2,2
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No,1,1,1

In [30]:
# Checking the Shape of Dataset
joined_data.shape

(79, 15)

In [31]:
# Third Dataset
# Importing dataset
df3 = pd.read_excel('additional_data.xlsx')
df3.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,CustomerID.1,Recency,Frequency_Score,Monetary_Score
0,C081,Male,37,50728,Chicago,West,11,75.757,2,In-store,2023-09-10,Yes,C081,2,2,1
1,C082,Female,48,69629,Los Angeles,Midwest,9,78.433,4,In-store,2023-07-15,No,C082,3,4,4
2,C083,Male,28,29184,Chicago,Northeast,7,82.794,3,Online,2023-08-25,Yes,C083,3,1,2
3,C084,Female,33,61265,Los Angeles,West,15,88.490,2,Online,2022-10-22,Yes,C084,4,1,3
4,C085,Female,30,63130,Houston,Midwest,13,108.749,3,Online,2023-04-01,Yes,C085,4,4,1

In [32]:
# Concatenating Multiple Datasets
final_data = (pd.concat([joined_data, df3])).reset_index(drop=True)
final_data.tail()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score,CustomerID.1
94,C096,Male,32,18600.0,Chicago,Northeast,12,123.003,4,Online,2022-02-03,Yes,4,2,3,C096
95,C097,Male,38,68525.0,Chicago,West,13,106.526,4,Online,2023-09-20,Yes,4,3,3,C097
96,C098,Female,24,73538.0,Houston,West,3,162.533,1,In-store,2023-11-04,Yes,2,1,1,C098
97,C099,Female,20,47251.0,Chicago,Midwest,5,145.404,2,In-store,2022-09-24,No,4,3,1,C099
98,C100,Male,39,52054.0,Chicago,Midwest,14,36.975,2,In-store,2023-05-03,No,1,4,4,C100

In [33]:
# Dropping Unnecessary Column from Dataset
final_data = final_data.drop('CustomerID.1', axis=1)
final_data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,Recency,Frequency_Score,Monetary_Score
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05 00:00:00,Yes,3,2,2
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08 00:00:00,Yes,3,3,3
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30 00:00:00,No,4,4,4
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01 00:00:00,No,2,2,2
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23 00:00:00,No,1,1,1

#### Data Analysis

In [34]:
freq_purchase_channel = final_data['Purchase_Channel'].value_counts()
freq_purchase_channel

Purchase_Channel
Online      65
In-store    34
Name: count, dtype: int64

In [35]:
perc_purchase_channel = freq_purchase_channel/len(final_data['Purchase_Channel'])*100
perc_purchase_channel

Purchase_Channel
Online      65.656566
In-store    34.343434
Name: count, dtype: float64

In [36]:
round(final_data.describe())

,Age,Income,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Recency,Frequency_Score,Monetary_Score
count,99.0,99.0,99.0,99.0,99.0,99.0,99.0,99.0
mean,35.0,58115.0,9.0,135687.0,3.0,3.0,3.0,3.0
std,10.0,18618.0,3.0,1349094.0,1.0,1.0,1.0,1.0
min,17.0,15531.0,1.0,37.0,0.0,1.0,1.0,1.0
25%,28.0,45724.0,7.0,76.0,2.0,2.0,2.0,2.0
50%,35.0,58033.0,10.0,98.0,3.0,3.0,3.0,3.0
75%,42.0,71484.0,12.0,121.0,3.0,4.0,4.0,4.0
max,54.0,107662.0,16.0,13423412.0,5.0,4.0,4.0,4.0

In [37]:
final_data = final_data[final_data['Average_Purchase_Amount'] != 13423411.958]

In [38]:
round(final_data.describe())

,Age,Income,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Recency,Frequency_Score,Monetary_Score
count,98.0,98.0,98.0,98.0,98.0,98.0,98.0,98.0
mean,35.0,58131.0,9.0,98.0,3.0,3.0,3.0,3.0
std,10.0,18713.0,3.0,29.0,1.0,1.0,1.0,1.0
min,17.0,15531.0,1.0,37.0,0.0,1.0,1.0,1.0
25%,28.0,45482.0,7.0,76.0,2.0,2.0,2.0,2.0
50%,35.0,58033.0,10.0,97.0,3.0,3.0,3.0,3.0
75%,42.0,71994.0,12.0,120.0,3.0,4.0,4.0,4.0
max,54.0,107662.0,16.0,193.0,5.0,4.0,4.0,4.0

In [39]:
city_purchase_amount = final_data.groupby('City')['Average_Purchase_Amount'].median()
city_purchase_amount

City
Chicago        102.1860
Houston         87.6615
Los Angeles    100.7250
New York        94.4690
Name: Average_Purchase_Amount, dtype: float64

In [40]:
pivot_table = final_data.pivot_table(index = 'Churn_Status', 
                                     values = ['Recency', 'Frequency_Score', 'Monetary_Score'], 
                                     aggfunc = {'Recency':'mean', 'Frequency_Score':'mean', 'Monetary_Score':'mean', 'Churn_Status':'count'})

In [41]:
pivot_table = pivot_table.rename(columns = {'Churn_Status':'Freq_churn', 
                                            'Recency':'Mean_recency', 
                                            'Frequency_Score':'Mean_FS', 'Monetary_Score':'Mean_MS'})

In [42]:
pivot_table

              Freq_churn   Mean_FS   Mean_MS  Mean_recency
Churn_Status
No                    43  2.744186  2.558140      2.720930
Yes                   55  2.509091  2.509091      2.618182

In [43]:
cross_tab = pd.crosstab(final_data['City'], final_data['Churn_Status'])
cross_tab

Churn_Status  No  Yes
City
Chicago        8   17
Houston       16   16
Los Angeles   10   14
New York       9    8

In [44]:
num_variables = final_data.select_dtypes(include = ['number']).columns

In [45]:
num_variables

Index(['Age', 'Income', 'Frequency_of_Purchases', 'Average_Purchase_Amount',
       'Customer_Lifespan_Months', 'Recency', 'Frequency_Score',
       'Monetary_Score'],
      dtype='object')

In [46]:
correl = round(final_data[num_variables].corr(), 3)
correl

,Age,Income,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Recency,Frequency_Score,Monetary_Score
Age,1.000,0.110,0.301,0.170,0.334,-0.048,-0.006,0.065
Income,0.110,1.000,-0.022,0.023,0.068,0.178,0.163,0.162
Frequency_of_Purchases,0.301,-0.022,1.000,0.704,0.762,-0.063,-0.065,-0.066
Average_Purchase_Amount,0.170,0.023,0.704,1.000,0.690,-0.029,-0.145,-0.191
Customer_Lifespan_Months,0.334,0.068,0.762,0.690,1.000,-0.073,-0.013,-0.001
Recency,-0.048,0.178,-0.063,-0.029,-0.073,1.000,0.761,0.743
Frequency_Score,-0.006,0.163,-0.065,-0.145,-0.013,0.761,1.000,0.819
Monetary_Score,0.065,0.162,-0.066,-0.191,-0.001,0.743,0.819,1.000